package com.generativecity.wallet.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.generativecity.wallet.viewmodel.NotificationsUiState

@Composable
fun NotificationsScreen(
    state: NotificationsUiState,
    onDecline: (String) -> Unit,
    onAccept: (String) -> Unit,
    onInstantPay: (String) -> Unit,
    onOpenCoupon: (String) -> Unit
) {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(Color(0xFFF8FAFC))
            .padding(16.dp)
    ) {
        Column(modifier = Modifier.fillMaxSize()) {
            Text("Notifications", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Black)
            Text(
                "These are generated by the backend AI loop when timing is good.",
                color = Color(0xFF64748B)
            )
            Spacer(modifier = Modifier.height(12.dp))

            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White)
            ) {
                Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                    Text("Last sync", fontWeight = FontWeight.Bold)
                    Text(
                        state.lastPollAtEpochMillis?.let { "Updated" } ?: "Waiting…",
                        color = Color(0xFF94A3B8)
                    )
                    Text(
                        "Open Home to see claimed rewards after accepting.",
                        color = Color(0xFF94A3B8)
                    )
                }
            }

            Spacer(modifier = Modifier.height(12.dp))

            // Backend-driven notifications are shown as system notifications + in Home inbox.
            // This screen is kept minimal until we wire a full in-app inbox list.
            Card(
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(18.dp),
                colors = CardDefaults.cardColors(containerColor = Color.White)
            ) {
                Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("Tip", fontWeight = FontWeight.Black)
                    Text(
                        "If you don’t see any offers, wait ~20 seconds (backend tick) and ensure Ollama is running.",
                        color = Color(0xFF475467)
                    )
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp), verticalAlignment = Alignment.CenterVertically) {
                        OutlinedButton(onClick = { /* no-op */ }) { Text("Decline") }
                        Button(onClick = { /* no-op */ }) { Text("Accept") }
                        Button(onClick = { /* no-op */ }) { Text("Pay Now") }
                    }
                }
            }
        }
    }
}
